name: CI

on:
  push:
    branches: [dev, staging, main]

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to WP Engine
      run: |
        echo "WPE_REPO_URL=${{ secrets.WPE_REPO_URL }}" >> $GITHUB_ENV
        echo "WPE_INSTALL_ID=${{ secrets.WPE_INSTALL_ID }}" >> $GITHUB_ENV
        echo "WPE_API_USER=${{ secrets.WPE_API_USER }}" >> $GITHUB_ENV
        echo "WPE_API_PASSWORD=${{ secrets.WPE_API_PASSWORD }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=${{ secrets.GIT_EMAIL }}" >> $GITHUB_ENV
        echo "GIT_NAME=${{ secrets.GIT_NAME }}" >> $GITHUB_ENV
        echo "ARTIFACT=temp.zip" >> $GITHUB_ENV

    - name: Run deployment script
      run: .github/workflows/deploy.sh

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to WP Engine
      run: |
        echo "WPE_REPO_URL=${{ secrets.WPE_REPO_URL }}" >> $GITHUB_ENV
        echo "WPE_INSTALL_ID=${{ secrets.WPE_INSTALL_ID }}" >> $GITHUB_ENV
        echo "WPE_API_USER=${{ secrets.WPE_API_USER }}" >> $GITHUB_ENV
        echo "WPE_API_PASSWORD=${{ secrets.WPE_API_PASSWORD }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=${{ secrets.GIT_EMAIL }}" >> $GITHUB_ENV
        echo "GIT_NAME=${{ secrets.GIT_NAME }}" >> $GITHUB_ENV
        echo "ARTIFACT=temp.zip" >> $GITHUB_ENV

    - name: Run deployment script
      run: .github/workflows/deploy.sh

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to WP Engine
      run: |
        echo "WPE_REPO_URL=${{ secrets.WPE_REPO_URL }}" >> $GITHUB_ENV
        echo "WPE_INSTALL_ID=${{ secrets.WPE_INSTALL_ID }}" >> $GITHUB_ENV
        echo "WPE_API_USER=${{ secrets.WPE_API_USER }}" >> $GITHUB_ENV
        echo "WPE_API_PASSWORD=${{ secrets.WPE_API_PASSWORD }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=${{ secrets.GIT_EMAIL }}" >> $GITHUB_ENV
        echo "GIT_NAME=${{ secrets.GIT_NAME }}" >> $GITHUB_ENV
        echo "ARTIFACT=temp.zip" >> $GITHUB_ENV

    - name: Run deployment script
      run: .github/workflows/deploy.sh
