name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Ensure working directory exists
      run: |
        echo "Creating working directory..."
        mkdir -p wp-content/themes/${{ github.event.repository.name }}
        echo "Directory structure:"
        ls -R wp-content/themes/
      working-directory: wp-content/themes

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Specify the PHP version you need
        extensions: mbstring, intl # Add any required PHP extensions

    - name: Debug - Check directory structure
      run: |
        echo "Current working directory:"
        pwd
        echo "Directory structure:"
        ls -R wp-content/themes/${{ github.event.repository.name }}

    - name: Install Composer dependencies
      run: composer install
      working-directory: wp-content/themes/${{ github.event.repository.name }}

    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: kingdomgamingp
        REMOTE_PATH: wp-content/themes/${{ github.event.repository.name }}/
