name: CI

on:
  push:
    branches: stage

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        DEV_ENV: kingdomggstg
        REMOTE_PATH: wp-content/themes/${{ github.event.repository.name }}/
